A IMDB dataset based movie recommendation engine powered by Python Sci-kit Learn

In [5]:
!pip install scikit-learn


[[1.  0.8]
 [0.8 1. ]]


In [61]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

text = ["django developer","django react developer"]
cv = CountVectorizer()

count_matrix = cv.fit_transform(text)

#print count_matrix.toarray()
similarity_scores = cosine_similarity(count_matrix)
print("Count Matrix in array")
print(count_matrix.toarray())
print("======= similarities with iteselfs and others in a list 100% to itself and 63% to second")
print(similarity_scores)
print("=======")
print(similarity_scores[0][1]*100)

Count Matrix in array
[[1 1 0]
 [1 1 1]]
======= similarities with iteselfs and others in a list 100% to itself and 63% to second
[[1.         0.81649658]
 [0.81649658 1.        ]]
81.6496580927726


In [65]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
###### helper functions #######
def get_title_from_index(index):
	return df[df.index == index]["title"].values[0]

def get_index_from_title(title):
	return df[df.title == title]["index"].values[0]

df = pd.read_csv("/content/movie_dataset.csv")

df.columns
#select features from which we will need recomendations
features = ['keywords','cast','genres','director']
df.head()
df['keywords']

#filling up NaN values with empty string of features (columns)
for feature in features:
	df[feature] = df[feature].fillna('')
 
#creat a single column concatanating all featues
def combine_features(row):
	try:
		return row['keywords'] +" "+row['cast']+" "+row["genres"]+" "+row["director"]
	except:
		print ("Error:", row)	

# after creating new column , call the combine_features funciton to insert it's values column wise (axis 1)
df["combined_features"] = df.apply(combine_features,axis=1)


df["combined_features"].head()

#inialized object to vectorize the features 
cv = CountVectorizer()

#it will create a matrix of combined features with words counting use count_matrix.toarray() to see the outputs in a human readable manner 
count_matrix = cv.fit_transform(df["combined_features"])
# print(count_matrix)
# now find the cosine similarities of the above matrix example  a list of movies of scores including comparison with itself 1.0 05 .8 .2 etc...  
cosine_sim = cosine_similarity(count_matrix)  
# print(cosine_sim)


#movie for which we need similar movies
movie_name = "Batman"

#getting the index number from name
movie_index = get_index_from_title(movie_name)

#making a list of movies with index and scores
similar_movies =  list(enumerate(cosine_sim[movie_index]))
# print(similar_movies)

#sort the similar movies in reverse order
sorted_similar_movies = sorted(similar_movies,key=lambda x:x[1],reverse=True)


i=0
for element in sorted_similar_movies:
    print(element[0])
    print(get_title_from_index(element[0]))
    i=i+1
    if i>50:  
      break

1359
Batman
428
Batman Returns
210
Batman & Robin
3
The Dark Knight Rises
65
The Dark Knight
119
Batman Begins
753
The Sentinel
2530
Beetlejuice
1035
Jonah Hex
2635
Funny Games
813
Superman
4638
Amidst the Devil's Wings
14
Man of Steel
4065
Mi America
2793
The Killer Inside Me
1803
Blood and Wine
2047
Megiddo: The Omega Code 2
2655
Dungeons & Dragons: Wrath of the Dragon God
3637
Kill the Messenger
278
Planet of the Apes
215
Fantastic 4: Rise of the Silver Surfer
1009
The Bone Collector
2313
The Mask
2858
The Postman Always Rings Twice
3372
Split Second
3630
Jekyll and Hyde ... Together Again
3774
Red State
207
Total Recall
299
Batman Forever
1512
A History of Violence
1792
Pain & Gain
2029
Underworld
3854
Batman: The Dark Knight Returns, Part 2
4675
The Grace Card
3306
Code of Honor
1827
Teenage Mutant Ninja Turtles II: The Secret of the Ooze
5
Spider-Man 3
2108
Edward Scissorhands
3326
Black November
3359
In Too Deep
4105
The Book of Mormon Movie, Volume 1: The Journey
30
Spider-Man 